/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocktail;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class CoctailApplication extends javax.swing.JFrame {
  
   ArrayList<Ingredients>ingrediant=new ArrayList<>();
    ArrayList<Cup>cups=new ArrayList<>();
            
   Blunder blunder = new Blunder(1500);  
   
    public CoctailApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameListOfFruites = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        volumeFruitTextField = new javax.swing.JTextField();
        caloriesFruitTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientsList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        addFruit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        chekSugger = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        RsystemColorCoctail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        GsystemColorCoctail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BsystemColorCoctail = new javax.swing.JTextField();
        BsystemColorFruit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RsystemColorFruit = new javax.swing.JTextField();
        GsystemColorFruit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        remainingCapacityTectField = new javax.swing.JTextField();
        addMilk = new javax.swing.JButton();
        milkVolumeTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        melkCalories = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addSuger = new javax.swing.JButton();
        moreFruites = new javax.swing.JButton();
        cupCombo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        poureButton = new javax.swing.JButton();
        BlendButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        caloriesCup = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        beforePoure = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        overallCalories = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ShowFileInformation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showLoadedObject = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Welcom to \"Amro Cocktail\"  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 12, 207, 17);

        NameListOfFruites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple(50cal/100ml)", "Orange(30cal/100ml)", "Banana(20cal/100ml)", "Grapes(20cal/100ml)", "Strawberry(50cal/100ml)", " " }));
        NameListOfFruites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameListOfFruitesActionPerformed(evt);
            }
        });
        jPanel1.add(NameListOfFruites);
        NameListOfFruites.setBounds(10, 80, 144, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Volume(ml)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 60, 73, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Calories");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(294, 64, 61, 15);
        jPanel1.add(volumeFruitTextField);
        volumeFruitTextField.setBounds(166, 80, 87, 30);
        jPanel1.add(caloriesFruitTextField);
        caloriesFruitTextField.setBounds(294, 80, 84, 30);

        jScrollPane1.setViewportView(ingredientsList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 267, 250, 263);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("List of Ingredients that you need to add for the blender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(12, 246, 319, 15);

        addFruit.setText("Add Fruit to the list ");
        addFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFruitActionPerformed(evt);
            }
        });
        jPanel1.add(addFruit);
        addFruit.setBounds(10, 120, 127, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Do you want to add Suger");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(11, 150, 165, 15);

        chekSugger.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chekSugger.setText("Yes I need  ");
        chekSugger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekSuggerActionPerformed(evt);
            }
        });
        jPanel1.add(chekSugger);
        chekSugger.setBounds(11, 171, 93, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("If you want to add milk, please set the volume that you need: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(122, 171, 348, 20);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setText("Save ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton);
        saveButton.setBounds(268, 488, 63, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Color of your coctail in RGB system");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(337, 282, 197, 15);
        jPanel1.add(RsystemColorCoctail);
        RsystemColorCoctail.setBounds(337, 324, 34, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("R");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(337, 303, 22, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("G");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(381, 303, 16, 15);
        jPanel1.add(GsystemColorCoctail);
        GsystemColorCoctail.setBounds(381, 324, 34, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("B");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(433, 303, 14, 15);
        jPanel1.add(BsystemColorCoctail);
        BsystemColorCoctail.setBounds(433, 324, 33, 30);
        jPanel1.add(BsystemColorFruit);
        BsystemColorFruit.setBounds(517, 80, 30, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Color of your Fruit in RGB system");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(396, 64, 300, 15);
        jPanel1.add(RsystemColorFruit);
        RsystemColorFruit.setBounds(396, 80, 34, 30);
        jPanel1.add(GsystemColorFruit);
        GsystemColorFruit.setBounds(457, 80, 32, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Blender has voume = 1500 ml");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(11, 40, 166, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Remaining volume after poure = ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 510, 183, 15);

        remainingCapacityTectField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        remainingCapacityTectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingCapacityTectFieldActionPerformed(evt);
            }
        });
        jPanel1.add(remainingCapacityTectField);
        remainingCapacityTectField.setBounds(520, 500, 80, 30);

        addMilk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addMilk.setText("Add milk to list");
        addMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMilkActionPerformed(evt);
            }
        });
        jPanel1.add(addMilk);
        addMilk.setBounds(337, 200, 123, 30);
        jPanel1.add(milkVolumeTextField);
        milkVolumeTextField.setBounds(480, 171, 92, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("milk has 50cal/100ml");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(443, 150, 120, 15);
        jPanel1.add(melkCalories);
        melkCalories.setBounds(590, 171, 84, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("melk's calories");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(581, 150, 101, 15);

        addSuger.setText("Add Suger");
        addSuger.setEnabled(false);
        addSuger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSugerActionPerformed(evt);
            }
        });
        jPanel1.add(addSuger);
        addSuger.setBounds(12, 205, 83, 30);

        moreFruites.setText("if you need more Fruits please click me ");
        moreFruites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreFruitesActionPerformed(evt);
            }
        });
        jPanel1.add(moreFruites);
        moreFruites.setBounds(156, 121, 251, 30);

        cupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cup with volume = 50ml", "cup with volume =100ml", "cup with volume = 150ml", " " }));
        jPanel1.add(cupCombo);
        cupCombo.setBounds(337, 376, 174, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Choose the cup that you need ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(340, 360, 174, 15);

        poureButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        poureButton.setText("poure");
        poureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poureButtonActionPerformed(evt);
            }
        });
        jPanel1.add(poureButton);
        poureButton.setBounds(337, 409, 65, 30);

        BlendButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BlendButton.setText("blend your Ingredient");
        BlendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlendButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BlendButton);
        BlendButton.setBounds(337, 241, 151, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Calories of the cup = ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(337, 441, 160, 15);

        caloriesCup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(caloriesCup);
        caloriesCup.setBounds(520, 440, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Total Volume before poure = ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(337, 473, 183, 15);

        beforePoure.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        beforePoure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beforePoureActionPerformed(evt);
            }
        });
        jPanel1.add(beforePoure);
        beforePoure.setBounds(520, 470, 80, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Overall Clories in Blender");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(552, 283, 132, 15);
        jPanel1.add(overallCalories);
        overallCalories.setBounds(552, 324, 87, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\1154-0243000040000-1.jpg")); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 0, 710, 540);

        jTabbedPane1.addTab("Welcome", jPanel1);

        ShowFileInformation.setText("ShowBlenderAndIngredientsAndCups");
        ShowFileInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFileInformationActionPerformed(evt);
            }
        });

        showLoadedObject.setColumns(20);
        showLoadedObject.setRows(5);
        jScrollPane2.setViewportView(showLoadedObject);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(ShowFileInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ShowFileInformation)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("forFilePart", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameListOfFruitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameListOfFruitesActionPerformed
        
    }//GEN-LAST:event_NameListOfFruitesActionPerformed

    private void chekSuggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekSuggerActionPerformed
        // TODO add your handling code here:
        addSuger.setEnabled(chekSugger.isSelected());
    }//GEN-LAST:event_chekSuggerActionPerformed

    private void addFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFruitActionPerformed
      try{                                     
     String FruitNmae = NameListOfFruites.getSelectedItem().toString();
     int volume = Integer.parseInt(volumeFruitTextField.getText());
     int r = Integer.parseInt(RsystemColorFruit.getText());
     int g = Integer.parseInt(GsystemColorFruit.getText());
     int b = Integer.parseInt(BsystemColorFruit.getText());
     int calories=0;
     if(NameListOfFruites.getSelectedIndex()==0)
          calories=volume/2;
      if(NameListOfFruites.getSelectedIndex()==1)
         calories=volume*3/5;
        
     if(NameListOfFruites.getSelectedIndex()==2)
         calories=volume/5;
         
     if(NameListOfFruites.getSelectedIndex()==3)
         calories=volume/5;
    if(NameListOfFruites.getSelectedIndex()==4)
         calories=volume/2;
    caloriesFruitTextField.setText(""+calories);
    
    Fruits fruits = new Fruits(volume, new Color(r, g, b), FruitNmae, calories);
   
    
        
        displayIngredientList();
       try {
           blunder.add(fruits);
           ingrediant.add(fruits);
       } catch (BlenderOverFlowException ex) {
           JOptionPane.showMessageDialog(this, "Blunder is full !!");
       }
      }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.toString(), "Error maybe in your input data", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_addFruitActionPerformed

    private void addMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMilkActionPerformed
        try{
        String milkName = "milk";
        int volume = Integer.parseInt(milkVolumeTextField.getText());
        //calories = 50cal/100ml
        int calories = volume/2;
        Milk milk = new Milk(milkName, calories, volume);
      
        
        displayIngredientList();
        melkCalories.setText(""+calories);
        
        try {
           blunder.add(milk);
           ingrediant.add(milk);
       } catch (BlenderOverFlowException ex) {
           JOptionPane.showMessageDialog(this, "Blunder is full !!");
       }
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.toString(), "Error maybe in your input data", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_addMilkActionPerformed

    private void addSugerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSugerActionPerformed
        // TODO add your handling code here:
        Suger suger = new Suger();
       
        
        displayIngredientList();
        try {
           blunder.add(suger);
           ingrediant.add(suger);
       } catch (BlenderOverFlowException ex) {
           JOptionPane.showMessageDialog(this, "Blunder is full !!");
       }
    }//GEN-LAST:event_addSugerActionPerformed

    private void moreFruitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreFruitesActionPerformed
        volumeFruitTextField.setText("");
        RsystemColorFruit.setText("");
        GsystemColorFruit.setText("");
        BsystemColorFruit.setText("");
        caloriesFruitTextField.setText("");
    }//GEN-LAST:event_moreFruitesActionPerformed

    private void poureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poureButtonActionPerformed
        // TODO add your handling code here:
        if (cupCombo.getSelectedIndex()==0){
            Cup cup = new Cup(50);
            
            try {
                beforePoure.setText(""+blunder.getVolume());
                blunder.pour(cup);
                cups.add(cup);
                remainingCapacityTectField.setText(""+blunder.getVolume());
                caloriesCup.setText(""+cup.getCalories());
            } catch (BlenderIsEmptyException ex) {
                JOptionPane.showMessageDialog(this, "Blunder is empty !!");
            }
        }
        if (cupCombo.getSelectedIndex()==1){
            Cup cup = new Cup(100);
            
            try {
                beforePoure.setText(""+blunder.getVolume());
                blunder.pour(cup);
                cups.add(cup);
                remainingCapacityTectField.setText(""+blunder.getVolume());
                caloriesCup.setText(""+cup.getCalories());
            } catch (BlenderIsEmptyException ex) {
                JOptionPane.showMessageDialog(this, "Blunder is empty !!");
            }
        }
        if (cupCombo.getSelectedIndex()==2){
            Cup cup = new Cup(150);
            
            try {
                beforePoure.setText(""+blunder.getVolume());
                blunder.pour(cup);
                cups.add(cup);
                remainingCapacityTectField.setText(""+blunder.getVolume());
                caloriesCup.setText(""+cup.getCalories());
            } catch (BlenderIsEmptyException ex) {
                JOptionPane.showMessageDialog(this, "Blunder is empty !!");
            }
        }
    }//GEN-LAST:event_poureButtonActionPerformed
    
    void displayIngredientList(){
   
       String []nameOfIngredient = new String[ingrediant.size()];
       for ( int i = 0; i <nameOfIngredient.length ; i++) {
           nameOfIngredient[i]=i+1+"-"+ingrediant.get(i).getName()+" has volume : "+ingrediant.get(i).getVolume()
                   +" ,and Calories : "+ingrediant.get(i).getCalories();
       }
       ingredientsList.setListData(nameOfIngredient);
   }
    private void BlendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlendButtonActionPerformed
        // TODO add your handling code here:
       try{
        blunder.blend();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Something wrong !!");
       }
        overallCalories.setText(""+blunder.getCalories());
        RsystemColorCoctail.setText(""+blunder.getColor().getR());
        GsystemColorCoctail.setText(""+blunder.getColor().getG());
        BsystemColorCoctail.setText(""+blunder.getColor().getB());
    }//GEN-LAST:event_BlendButtonActionPerformed

    private void beforePoureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beforePoureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beforePoureActionPerformed

    private void remainingCapacityTectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingCapacityTectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainingCapacityTectFieldActionPerformed

    private void ShowFileInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFileInformationActionPerformed
        // TODO add your handling code here:
         ArrayList<Ingredients>ingrediant1=null;
         Blunder b=null;
         ArrayList<Cup>cups1=null;
        try{
            
             ObjectInputStream objectInputStream = new ObjectInputStream(new FileInputStream("ingredientWithBlenderAndCups.dat"));
                   
            try{
            String str ="";
          
           while (true){
                 ingrediant1 =(ArrayList) objectInputStream.readObject();
               b=(Blunder)objectInputStream.readObject();
             cups1=(ArrayList) objectInputStream.readObject();
               str="Our Blender: "+"\n"+b.getInfo()+"\n"+"Ingredient : ";
               for (int i = 0; i < ingrediant1.size(); i++) {
                   str+=ingrediant1.get(i).getInfo()+"\n";
               }
               str+="\n"+"Cups :";
                for(int i =0;i<cups1.size();i++){
                str+=cups1.get(i).getInfo()+"\n";
                }
              showLoadedObject.setText(str);
             }
             
             }
             catch(EOFException eof ){
            JOptionPane.showMessageDialog(this,"end of file !!");
             }
            objectInputStream.close();
   }
  catch(IOException ioe){
 JOptionPane.showMessageDialog(this,"Something wrong in your file  !!");
   }
   catch(ClassNotFoundException classNotFoundException){
  JOptionPane.showMessageDialog(this,"Something wrong in your class  !!");
   }                 

           
    }//GEN-LAST:event_ShowFileInformationActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        volumeFruitTextField.setText("");
        RsystemColorFruit.setText("");
        GsystemColorFruit.setText("");
        BsystemColorFruit.setText("");
        caloriesFruitTextField.setText("");
        overallCalories.setText("");
        RsystemColorCoctail.setText("");
        GsystemColorCoctail.setText("");
        BsystemColorCoctail.setText("");
        beforePoure.setText("");
        milkVolumeTextField.setText("");
        remainingCapacityTectField.setText("");
         caloriesCup.setText("");
        String []nameOfIngredient = new String[ingrediant.size()];
         for ( int i = 0; i <nameOfIngredient.length ; i++) {
           nameOfIngredient[i]="";
       }
       ingredientsList.setListData(nameOfIngredient);
       melkCalories.setText("");
        caloriesCup.setText("");
         try{
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(new FileOutputStream("ingredientWithBlenderAndCups.dat"));
        objectOutputStream.writeObject(ingrediant);
        objectOutputStream.writeObject(blunder);
        objectOutputStream.writeObject(cups);
        objectOutputStream.close();
    }catch(IOException iOexception){
        JOptionPane.showMessageDialog(this,"Something wrong in your file  !!");
    }
    }//GEN-LAST:event_saveButtonActionPerformed
               
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoctailApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlendButton;
    private javax.swing.JTextField BsystemColorCoctail;
    private javax.swing.JTextField BsystemColorFruit;
    private javax.swing.JTextField GsystemColorCoctail;
    private javax.swing.JTextField GsystemColorFruit;
    private javax.swing.JComboBox<String> NameListOfFruites;
    private javax.swing.JTextField RsystemColorCoctail;
    private javax.swing.JTextField RsystemColorFruit;
    private javax.swing.JButton ShowFileInformation;
    private javax.swing.JButton addFruit;
    private javax.swing.JButton addMilk;
    private javax.swing.JButton addSuger;
    private javax.swing.JTextField beforePoure;
    private javax.swing.JTextField caloriesCup;
    private javax.swing.JTextField caloriesFruitTextField;
    private javax.swing.JCheckBox chekSugger;
    private javax.swing.JComboBox<String> cupCombo;
    private javax.swing.JList<String> ingredientsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField melkCalories;
    private javax.swing.JTextField milkVolumeTextField;
    private javax.swing.JButton moreFruites;
    private javax.swing.JTextField overallCalories;
    private javax.swing.JButton poureButton;
    private javax.swing.JTextField remainingCapacityTectField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea showLoadedObject;
    private javax.swing.JTextField volumeFruitTextField;
    // End of variables declaration//GEN-END:variables
}
