/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocktail;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class CoctailApplication extends javax.swing.JFrame {
  
   ArrayList<Ingredients>ingrediant=new ArrayList<>();
    ArrayList<Cup>cups=new ArrayList<>();
            
   Blunder blunder = new Blunder(1500);  
   
    public CoctailApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameListOfFruites = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        volumeFruitTextField = new javax.swing.JTextField();
        caloriesFruitTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientsList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        addFruit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        chekSugger = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        RsystemColorCoctail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        GsystemColorCoctail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BsystemColorCoctail = new javax.swing.JTextField();
        BsystemColorFruit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RsystemColorFruit = new javax.swing.JTextField();
        GsystemColorFruit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        remainingCapacityTectField = new javax.swing.JTextField();
        addMilk = new javax.swing.JButton();
        milkVolumeTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        melkCalories = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addSuger = new javax.swing.JButton();
        moreFruites = new javax.swing.JButton();
        cupCombo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        poureButton = new javax.swing.JButton();
        BlendButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        caloriesCup = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        beforePoure = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        overallCalories = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ShowFileInformation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showLoadedObject = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Welcom to \"Amro Cocktail\" , we are not alone, but we are the best    :)");

        NameListOfFruites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple(50cal/100ml)", "Orange(30cal/100ml)", "Banana(20cal/100ml)", "Grapes(20cal/100ml)", "Strawberry(50cal/100ml)", " " }));
        NameListOfFruites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameListOfFruitesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Volume(ml)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Calories");

        jScrollPane1.setViewportView(ingredientsList);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("List of Ingredients that you need to add for the blender");

        addFruit.setText("Add Fruit to the list ");
        addFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFruitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Do you want to add Suger");

        chekSugger.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chekSugger.setText("Yes I need  ");
        chekSugger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekSuggerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("If you want to add milk, please set the volume that you need: ");

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setText("Save ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Color of your coctail in RGB system");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("R");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("G");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("B");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Color of your Fruit in RGB system");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Blender has voume = 1500 ml");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Remaining volume after poure = ");

        remainingCapacityTectField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        remainingCapacityTectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingCapacityTectFieldActionPerformed(evt);
            }
        });

        addMilk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addMilk.setText("Add milk to list");
        addMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMilkActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("milk has 50cal/100ml");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("melk's calories");

        addSuger.setText("Add Suger");
        addSuger.setEnabled(false);
        addSuger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSugerActionPerformed(evt);
            }
        });

        moreFruites.setText("if you need more Fruits please click me ");
        moreFruites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreFruitesActionPerformed(evt);
            }
        });

        cupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cup with volume = 50ml", "cup with volume =100ml", "cup with volume = 150ml", " " }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Choose the cup that you need ");

        poureButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        poureButton.setText("poure");
        poureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poureButtonActionPerformed(evt);
            }
        });

        BlendButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BlendButton.setText("blend your Ingredient");
        BlendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlendButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Calories of the cup = ");

        caloriesCup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Total Volume before poure = ");

        beforePoure.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        beforePoure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beforePoureActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Overall Clories in Blender");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameListOfFruites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(volumeFruitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caloriesFruitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RsystemColorFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(GsystemColorFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(BsystemColorFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveButton))
                                    .addComponent(addSuger)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(27, 27, 27))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(beforePoure, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(remainingCapacityTectField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(caloriesCup))
                                        .addGap(90, 90, 90))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BlendButton)
                                                    .addComponent(poureButton)
                                                    .addComponent(addMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(RsystemColorCoctail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(GsystemColorCoctail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(BsystemColorCoctail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jLabel17)
                                                    .addComponent(cupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 23, Short.MAX_VALUE))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(overallCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19))
                                        .addGap(2, 2, 2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addFruit)
                                .addGap(18, 18, 18)
                                .addComponent(moreFruites, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chekSugger)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(milkVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(melkCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameListOfFruites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumeFruitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caloriesFruitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RsystemColorFruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GsystemColorFruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BsystemColorFruit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFruit)
                    .addComponent(moreFruites))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chekSugger)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(milkVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(melkCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addSuger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(addMilk)
                        .addGap(18, 18, 18)
                        .addComponent(BlendButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RsystemColorCoctail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GsystemColorCoctail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BsystemColorCoctail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(26, 26, 26)
                                .addComponent(overallCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(poureButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(caloriesCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(beforePoure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(remainingCapacityTectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Welcome", jPanel1);

        ShowFileInformation.setText("ShowBlenderAndIngredientsAndCups");
        ShowFileInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFileInformationActionPerformed(evt);
            }
        });

        showLoadedObject.setColumns(20);
        showLoadedObject.setRows(5);
        jScrollPane2.setViewportView(showLoadedObject);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(ShowFileInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ShowFileInformation)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("forFilePart", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameListOfFruitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameListOfFruitesActionPerformed
        
    }//GEN-LAST:event_NameListOfFruitesActionPerformed

    private void chekSuggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekSuggerActionPerformed
        // TODO add your handling code here:
        addSuger.setEnabled(chekSugger.isSelected());
    }//GEN-LAST:event_chekSuggerActionPerformed

    private void addFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFruitActionPerformed
      try{                                     
     String FruitNmae = NameListOfFruites.getSelectedItem().toString();
     int volume = Integer.parseInt(volumeFruitTextField.getText());
     int r = Integer.parseInt(RsystemColorFruit.getText());
     int g = Integer.parseInt(GsystemColorFruit.getText());
     int b = Integer.parseInt(BsystemColorFruit.getText());
     int calories=0;
     if(NameListOfFruites.getSelectedIndex()==0)
          calories=volume/2;
      if(NameListOfFruites.getSelectedIndex()==1)
         calories=volume*3/5;
        
     if(NameListOfFruites.getSelectedIndex()==2)
         calories=volume/5;
         
     if(NameListOfFruites.getSelectedIndex()==3)
         calories=volume/5;
    if(NameListOfFruites.getSelectedIndex()==4)
         calories=volume/2;
    caloriesFruitTextField.setText(""+calories);
    
    Fruits fruits = new Fruits(volume, new Color(r, g, b), FruitNmae, calories);
   
    
        
        displayIngredientList();
       try {
           blunder.add(fruits);
           ingrediant.add(fruits);
       } catch (BlenderOverFlowException ex) {
           JOptionPane.showMessageDialog(this, "Blunder is full !!");
       }
      }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.toString(), "Error maybe in your input data", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_addFruitActionPerformed

    private void addMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMilkActionPerformed
        try{
        String milkName = "milk";
        int volume = Integer.parseInt(milkVolumeTextField.getText());
        //calories = 50cal/100ml
        int calories = volume/2;
        Milk milk = new Milk(milkName, calories, volume);
      
        
        displayIngredientList();
        melkCalories.setText(""+calories);
        
        try {
           blunder.add(milk);
           ingrediant.add(milk);
       } catch (BlenderOverFlowException ex) {
           JOptionPane.showMessageDialog(this, "Blunder is full !!");
       }
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.toString(), "Error maybe in your input data", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_addMilkActionPerformed

    private void addSugerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSugerActionPerformed
        // TODO add your handling code here:
        Suger suger = new Suger();
       
        
        displayIngredientList();
        try {
           blunder.add(suger);
           ingrediant.add(suger);
       } catch (BlenderOverFlowException ex) {
           JOptionPane.showMessageDialog(this, "Blunder is full !!");
       }
    }//GEN-LAST:event_addSugerActionPerformed

    private void moreFruitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreFruitesActionPerformed
        volumeFruitTextField.setText("");
        RsystemColorFruit.setText("");
        GsystemColorFruit.setText("");
        BsystemColorFruit.setText("");
        caloriesFruitTextField.setText("");
    }//GEN-LAST:event_moreFruitesActionPerformed

    private void poureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poureButtonActionPerformed
        // TODO add your handling code here:
        if (cupCombo.getSelectedIndex()==0){
            Cup cup = new Cup(50);
            
            try {
                beforePoure.setText(""+blunder.getVolume());
                blunder.pour(cup);
                cups.add(cup);
                remainingCapacityTectField.setText(""+blunder.getVolume());
                caloriesCup.setText(""+cup.getCalories());
            } catch (BlenderIsEmptyException ex) {
                JOptionPane.showMessageDialog(this, "Blunder is empty !!");
            }
        }
        if (cupCombo.getSelectedIndex()==1){
            Cup cup = new Cup(100);
            
            try {
                beforePoure.setText(""+blunder.getVolume());
                blunder.pour(cup);
                cups.add(cup);
                remainingCapacityTectField.setText(""+blunder.getVolume());
                caloriesCup.setText(""+cup.getCalories());
            } catch (BlenderIsEmptyException ex) {
                JOptionPane.showMessageDialog(this, "Blunder is empty !!");
            }
        }
        if (cupCombo.getSelectedIndex()==2){
            Cup cup = new Cup(150);
            
            try {
                beforePoure.setText(""+blunder.getVolume());
                blunder.pour(cup);
                cups.add(cup);
                remainingCapacityTectField.setText(""+blunder.getVolume());
                caloriesCup.setText(""+cup.getCalories());
            } catch (BlenderIsEmptyException ex) {
                JOptionPane.showMessageDialog(this, "Blunder is empty !!");
            }
        }
    }//GEN-LAST:event_poureButtonActionPerformed
    
    void displayIngredientList(){
   
       String []nameOfIngredient = new String[ingrediant.size()];
       for ( int i = 0; i <nameOfIngredient.length ; i++) {
           nameOfIngredient[i]=i+1+"-"+ingrediant.get(i).getName()+" has volume : "+ingrediant.get(i).getVolume()
                   +" ,and Calories : "+ingrediant.get(i).getCalories();
       }
       ingredientsList.setListData(nameOfIngredient);
   }
    private void BlendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlendButtonActionPerformed
        // TODO add your handling code here:
       try{
        blunder.blend();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Something wrong !!");
       }
        overallCalories.setText(""+blunder.getCalories());
        RsystemColorCoctail.setText(""+blunder.getColor().getR());
        GsystemColorCoctail.setText(""+blunder.getColor().getG());
        BsystemColorCoctail.setText(""+blunder.getColor().getB());
    }//GEN-LAST:event_BlendButtonActionPerformed

    private void beforePoureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beforePoureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beforePoureActionPerformed

    private void remainingCapacityTectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingCapacityTectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainingCapacityTectFieldActionPerformed

    private void ShowFileInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFileInformationActionPerformed
        // TODO add your handling code here:
         ArrayList<Ingredients>ingrediant1=null;
         Blunder b=null;
         ArrayList<Cup>cups1=null;
        try{
            
             ObjectInputStream objectInputStream = new ObjectInputStream(new FileInputStream("ingredientWithBlenderAndCups.dat"));
                   
            try{
            String str ="";
          
           while (true){
                 ingrediant1 =(ArrayList) objectInputStream.readObject();
               b=(Blunder)objectInputStream.readObject();
             cups1=(ArrayList) objectInputStream.readObject();
               str="Our Blender: "+"\n"+b.getInfo()+"\n"+"Ingredient : ";
               for (int i = 0; i < ingrediant1.size(); i++) {
                   str+=ingrediant1.get(i).getInfo()+"\n";
               }
               str+="\n"+"Cups :";
                for(int i =0;i<cups1.size();i++){
                str+=cups1.get(i).getInfo()+"\n";
                }
              showLoadedObject.setText(str);
             }
             
             }
             catch(EOFException eof ){
            JOptionPane.showMessageDialog(this,"end of file !!");
             }
            objectInputStream.close();
   }
  catch(IOException ioe){
 JOptionPane.showMessageDialog(this,"Something wrong in your file  !!");
   }
   catch(ClassNotFoundException classNotFoundException){
  JOptionPane.showMessageDialog(this,"Something wrong in your class  !!");
   }                 

           
    }//GEN-LAST:event_ShowFileInformationActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        volumeFruitTextField.setText("");
        RsystemColorFruit.setText("");
        GsystemColorFruit.setText("");
        BsystemColorFruit.setText("");
        caloriesFruitTextField.setText("");
        overallCalories.setText("");
        RsystemColorCoctail.setText("");
        GsystemColorCoctail.setText("");
        BsystemColorCoctail.setText("");
        beforePoure.setText("");
        milkVolumeTextField.setText("");
        remainingCapacityTectField.setText("");
         caloriesCup.setText("");
        String []nameOfIngredient = new String[ingrediant.size()];
         for ( int i = 0; i <nameOfIngredient.length ; i++) {
           nameOfIngredient[i]="";
       }
       ingredientsList.setListData(nameOfIngredient);
       melkCalories.setText("");
        caloriesCup.setText("");
         try{
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(new FileOutputStream("ingredientWithBlenderAndCups.dat"));
        objectOutputStream.writeObject(ingrediant);
        objectOutputStream.writeObject(blunder);
        objectOutputStream.writeObject(cups);
        objectOutputStream.close();
    }catch(IOException iOexception){
        JOptionPane.showMessageDialog(this,"Something wrong in your file  !!");
    }
    }//GEN-LAST:event_saveButtonActionPerformed
               
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoctailApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoctailApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlendButton;
    private javax.swing.JTextField BsystemColorCoctail;
    private javax.swing.JTextField BsystemColorFruit;
    private javax.swing.JTextField GsystemColorCoctail;
    private javax.swing.JTextField GsystemColorFruit;
    private javax.swing.JComboBox<String> NameListOfFruites;
    private javax.swing.JTextField RsystemColorCoctail;
    private javax.swing.JTextField RsystemColorFruit;
    private javax.swing.JButton ShowFileInformation;
    private javax.swing.JButton addFruit;
    private javax.swing.JButton addMilk;
    private javax.swing.JButton addSuger;
    private javax.swing.JTextField beforePoure;
    private javax.swing.JTextField caloriesCup;
    private javax.swing.JTextField caloriesFruitTextField;
    private javax.swing.JCheckBox chekSugger;
    private javax.swing.JComboBox<String> cupCombo;
    private javax.swing.JList<String> ingredientsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField melkCalories;
    private javax.swing.JTextField milkVolumeTextField;
    private javax.swing.JButton moreFruites;
    private javax.swing.JTextField overallCalories;
    private javax.swing.JButton poureButton;
    private javax.swing.JTextField remainingCapacityTectField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea showLoadedObject;
    private javax.swing.JTextField volumeFruitTextField;
    // End of variables declaration//GEN-END:variables
}
